name: Auto Create PR for rewrite/x

on:
  push:
    branches:
      - rewrite/x

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: rewrite/x
          title: 'Auto PR: main <- rewrite/x'
          body: 'This is an automated pull request to merge changes from rewrite/x into main.'