name: testYaml

# mainにpushされた時
on:
    push:
        branches:
        - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # テスト用のファイル編集
    - name: Edit test file
      run: |
        echo "Hello, world!" > test.txt

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update generated files"

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.PULL_REQUEST_TOKEN }}
        commit-message: "Update generated files"
        branch: update-generated-files
        title: "Update generated files"
        body: "This PR updates the generated files."
        labels: "auto-merge"
        base: main
        delete-branch: true

    - name: Enable auto-merge
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
        token: ${{ secrets.PULL_REQUEST_TOKEN }}
        